# 시작할 때 고려할 점 

이 장에서는 개인 경험에 비추어 콰르토로 문서를 작성할 때 고려할 점들과 권고사항에 대해서 설명하고자 한다.

## 어떤 언어를 기반으로, 어떤 텍스트 에디터에서 글을 쓸 것인가?

콰르토가 익숙해지면 코드를 하나도 쓰지 않고 그냥 일반 워드 프로세서처럼 쓸 수 있겠지만, 보통의 경우라면 R 언어 또는 파이썬 언어(또는 둘 다)를 알고 있고, 이 자산을 활용하여 글을 쓰고자 할 것이다. R 언어 사용자들은 RStudio 통합개발환경을 주로 사용하고, 파이썬 언어 사용자들은 주피터 노트북/주피터랩을 많이 사용할 것이다. 조금 더 나간 경우에는 VS Code도 사용하고 있을 것이다. 

콰르토가 R, 파이썬 언어 이외에 줄리아(Julia)와 옵저버블제이에스(ObservableJS)를 통한 자바스크립트 언어를 사용할 수 있지만 여기선 R, 파이썬 언어에만 국한하여 설명한다. 또 주피터 노트북에서 [IRkernel](https://irkernel.github.io)을 사용하면 주피터 노트북에서 R 언어를 사용할 수 있고, RStudio에서 [reticulate](https://rstudio.github.io/reticulate/) 패키지를 사용하면 R 언어 환경에 파이썬 언어를 사용할 수도 있다. 더 나간다면 주피터 노트북이 다양한 커널을 통해서 다양한 언어에 연결하여 사용할 수 있는 도구이고, 콰르토가 주피턴 엔진을 사용할 수 있기 때문에 콰르토를 통해서 무수히 많은 언어들과 연결하여 사용할 수 있을 수도 있다. 심지어 [SoS Notebook](https://vatlab.github.io/sos-docs/notebook.html)을 사용한다면 한 문서 안에서 코드별로 여러 언어를 연결하여 사용할 수도 있을지도 모른다. 내 경우에는 R 또는 파이썬 언어로도 충분해서 그런 내용을 시도해 보지 않있가. 그리고 이 책에서도 **이와 같은 (고급) 내용들은 다루지 않으려고 한다**.

### R 언어 사용자 


### 파이썬 언어 사용자 








## 어떤 포맷의 문서를 만들려고 하는가? 

## 어떻게 콰르토를 배울 것인가?
